# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.

obj-$(CONFIG_NVIDIA_PCIE_TEGRA264_ST) += controller/
obj-$(CONFIG_NVIDIA_PCIE_TEGRA264_ST) += endpoint/
