# SPDX-License-Identifier: GPL-2.0-only
# SPDX-FileCopyrightText: Copyright (c) 2022-2025 NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.

obj-$(CONFIG_PCIE_TEGRA194_EP) += pci-epf-dma-test.o
obj-$(CONFIG_TEGRA_HOST1X) += pci-epf-tegra-vnet.o
